{
 "title": "DashboardName",
 "description": "Dashboard to get an overview of one server",
 "tags": [
  "DataSource",
  "virtual",
  "tagul"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count by(cpu)(node_cpu_seconds_total{job=~\"JobName\",instance=~\"JobName:9100\"}))"
    }
   ]
  },
  {
   "title": "Disk Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{job=~\"JobName\",instance=~\"JobName:9100\", device=~\"/dev/.*\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"JobName\",instance=~\"JobName:9100\"}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{job=~\"JobName\",instance=~\"JobName:9100\"} / count by(job, instance)(count by(job, instance, cpu)(node_cpu_seconds_total{job=~\"JobName\",instance=~\"JobName:9100\"}))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=~\"JobName\",instance=~\"JobName:9100\"}"
    }
   ]
  },
  { "title": " IP Address", "type": "text", "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 }, "options": { "content": "# IP_ADDR" } },
  {
   "title": "Memory Distribution",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"JobName\",instance=~\"JobName:9100\"} - node_memory_MemFree_bytes{job=~\"JobName\",instance=~\"JobName:9100\"} - node_memory_Cached_bytes{job=~\"JobName\",instance=~\"JobName:9100\"} - node_memory_Buffers{job=~\"JobName\",instance=~\"JobName:9100\"} - node_memory_Slab{job=~\"JobName\",instance=~\"JobName:9100\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=~\"JobName\",instance=~\"JobName:9100\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=~\"JobName\",instance=~\"JobName:9100\"} + node_memory_Slab_bytes{job=~\"JobName\",instance=~\"JobName:9100\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=~\"JobName\",instance=~\"JobName:9100\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{job=~\"JobName\",instance=~\"JobName:9100\"} - node_memory_MemFree_bytes{job=~\"JobName\",instance=~\"JobName:9100\"} - node_memory_Cached_bytes{job=~\"JobName\",instance=~\"JobName:9100\"} - node_memory_Buffers_bytes{job=~\"JobName\",instance=~\"JobName:9100\"} - node_memory_Slab_bytes{job=~\"JobName\",instance=~\"JobName:9100\"}) / node_memory_MemTotal_bytes{job=~\"JobName\",instance=~\"JobName:9100\"} * 100",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"idle\", job=~\"JobName\",instance=~\"JobName:9100\"}[5m])) * 100",
     "legendFormat": "Idle"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"iowait\", job=~\"JobName\",instance=~\"JobName:9100\"}[5m])) * 100",
     "legendFormat": "IOwait"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"irq\", job=~\"JobName\",instance=~\"JobName:9100\"}[5m])) * 100",
     "legendFormat": "Irq"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"softirq\", job=~\"JobName\",instance=~\"JobName:9100\"}[5m])) * 100",
     "legendFormat": "SoftIrq"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"system\", job=~\"JobName\",instance=~\"JobName:9100\"}[5m])) * 100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"user\", job=~\"JobName\",instance=~\"JobName:9100\"}[5m])) * 100",
     "legendFormat": "User"
    }
   ]
  },
  {
   "title": "System load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=~\"JobName\",instance=~\"JobName:9100\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{job=~\"JobName\",instance=~\"JobName:9100\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{job=~\"JobName\",instance=~\"JobName:9100\"}",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=~\"JobName\",instance=~\"JobName:9100\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m])*8",
     "legendFormat": "{{ device }} OUT"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=~\"JobName\",instance=~\"JobName:9100\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m])*8",
     "legendFormat": "{{ device }} IN"
    }
   ]
  },
  {
   "title": "Disk Space ( /all )",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1-(node_filesystem_free_bytes{job=~\"JobName\",instance=~\"JobName:9100\", mountpoint=~\"/\",fstype=\"ext4\"}/ node_filesystem_size_bytes{job=~\"JobName\",instance=~\"JobName:9100\", mountpoint=~\"/\",fstype=\"ext4\"}))*100 ",
     "legendFormat": "Used (/)"
    },
    {
     "expr": "(1-(node_filesystem_free_bytes{job=~\"JobName\",instance=~\"JobName:9100\", mountpoint=~\"/boot/efi\",fstype=\"vfat\"}/ node_filesystem_size_bytes{job=~\"JobName\",instance=~\"JobName:9100\", mountpoint=~\"/boot/efi\",fstype=\"vfat\"}))*100 ",
     "legendFormat": "Used (/boot)"
    }
   ]
  },
  {
   "title": "IOPs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_reads_completed_total{job=~\"JobName\",instance=~\"JobName:9100\"}[5m]))",
     "legendFormat": "reads per second"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_writes_completed_total{job=~\"JobName\",instance=~\"JobName:9100\"}[5m]))",
     "legendFormat": "writes per second"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_io_time_seconds_total{job=~\"JobName\",instance=~\"JobName:9100\"}[5m]))",
     "legendFormat": "io time"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_reads_completed_total{job=~\"JobName\",instance=~\"JobName:9100\"}[5m])) + sum by (instance) (irate(node_disk_writes_completed_total{job=~\"JobName\",instance=~\"JobName:9100\"}[5m]))",
     "legendFormat": "IOPS"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_read_bytes_total{job=~\"JobName\",instance=~\"JobName:9100\"}[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_written_bytes_total{job=~\"JobName\",instance=~\"JobName:9100\"}[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_read_bytes_total{job=~\"JobName\",instance=~\"JobName:9100\"}[5m])) + sum by (instance) (irate(node_disk_written_bytes_total{job=~\"JobName\",instance=~\"JobName:9100\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Time Sync",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "time()-node_time{job=~\"JobName\",instance=~\"JobName:9100\"} or time()-node_time_seconds{job=~\"JobName\",instance=~\"JobName:9100\"}"
    }
   ]
  }
 ]
}