{
 "title": "DashboardName",
 "description": "Dashboard to get an overview of one server",
 "tags": [
  "DataSource",
  "Windows-Exporter",
  "tag"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count by(core)(windows_cpu_time_total{job=~\"JobName\",instance=~\"JobName:9182\"}))"
    }
   ]
  },
  {
   "title": "Disk Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(windows_logical_disk_size_bytes{job=~\"JobName\",instance=~\"JobName:9182\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{job=~\"JobName\",instance=~\"JobName:9182\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - windows_system_system_up_time{job=~\"JobName\",instance=~\"JobName:9182\"}"
    }
   ]
  },
  { "title": " IP Adress", "type": "text", "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 }, "options": { "content": "# IP_ADDR" } },
  {
   "title": "Memory Distribution",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{job=~\"JobName\",instance=~\"JobName:9182\"} - windows_os_physical_memory_free_bytes{job=~\"JobName\",instance=~\"JobName:9182\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes{job=~\"JobName\",instance=~\"JobName:9182\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(windows_cs_physical_memory_bytes{job=~\"JobName\",instance=~\"JobName:9182\"} - windows_os_physical_memory_free_bytes{job=~\"JobName\",instance=~\"JobName:9182\"}) / windows_cs_physical_memory_bytes{job=~\"JobName\",instance=~\"JobName:9182\"} * 100",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(irate(windows_cpu_time_total{mode=\"idle\", job=~\"JobName\",instance=~\"JobName:9182\"}[5m])) * 100",
     "legendFormat": "Idle"
    },
    {
     "expr": "avg(irate(windows_cpu_time_total{mode=\"dpc\", job=~\"JobName\",instance=~\"JobName:9182\"}[5m])) * 100",
     "legendFormat": "DPC"
    },
    {
     "expr": "avg(irate(windows_cpu_time_total{mode=\"interrupt\", job=~\"JobName\",instance=~\"JobName:9182\"}[5m])) * 100",
     "legendFormat": "Interrupt"
    },
    {
     "expr": "avg(irate(windows_cpu_time_total{mode=\"privileged\", job=~\"JobName\",instance=~\"JobName:9182\"}[5m])) * 100",
     "legendFormat": "Privileged"
    },
    {
     "expr": "avg(irate(windows_cpu_time_total{mode=\"user\", job=~\"JobName\",instance=~\"JobName:9182\"}[5m])) * 100",
     "legendFormat": "User"
    }
   ]
  },
  {
   "title": "Disk Space ( /all )",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1-(windows_logical_disk_free_bytes{volume=\"C:\",job=~\"JobName\",instance=~\"JobName:9182\"} / windows_logical_disk_size_bytes{volume=\"C:\",job=~\"JobName\",instance=~\"JobName:9182\"}))*100",
     "legendFormat": "Used (C:)"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "irate(windows_net_bytes_sent_total{instance=\"JobName:9182\", job=\"JobName\", nic=\"vmxnet3_Ethernet_Adapter\"}[5m])*8/1024/1024",
     "legendFormat": "{{nic}} OUT"
    },
    {
     "expr": "irate(windows_net_bytes_received_total{instance=\"JobName:9182\", job=\"JobName\", nic=\"vmxnet3_Ethernet_Adapter\"}[5m])*8/1024/1024",
     "legendFormat": "{{nic}} IN"
    },
    {
     "expr": "irate(windows_net_bytes_sent_total{instance=\"JobName:9182\", job=\"JobName\", nic=\"vmxnet3_Ethernet_Adapter__2\"}[5m])*8/1024/1024",
     "legendFormat": "{{nic}} OUT"
    },
    {
     "expr": "irate(windows_net_bytes_received_total{instance=\"JobName:9182\", job=\"JobName\", nic=\"vmxnet3_Ethernet_Adapter__2\"}[5m])*8/1024/1024",
     "legendFormat": "{{nic}} IN"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(windows_logical_disk_read_bytes_total{job=~\"JobName\",instance=~\"JobName:9182\"}[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum by (instance) (irate(windows_logical_disk_write_bytes_total{job=~\"JobName\",instance=~\"JobName:9182\"}[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum by (instance) (irate(windows_logical_disk_read_bytes_total{job=~\"JobName\",instance=~\"JobName:9182\"}[5m])) + sum by (instance) (irate(windows_logical_disk_write_bytes_total{job=~\"JobName\",instance=~\"JobName:9182\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  }
 ]
}